linters:
  presets:
    - bugs
    - unused
    - complexity
    - format
    - performance
    - style
  disable:
    - exhaustivestruct

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoglobals
        - wrapcheck