version: 2
jobs:
  install:
    docker: 
      - image: circleci/golang:1.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: make install
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: make build-all
      - persist_to_workspace:
          root: bin
          paths:
            - conf-sync
  
  test:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: make test
  
  lint:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
      - run: make lint
  
  release:
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - attach_workspace:
          at: ~project/bin/
      - run: make release

workflows:
  version: 2

  build-test-release:
    jobs:
      - install
      - lint
      - build: 
          requires: 
            - install
      - test: 
          requires: 
            - install
      - release:
          requires:
            - lint
            - build
            - test
          filters:
            branches:
              only:
                - master
                - beta
                - ci-test