version: 2

references: 
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

jobs:
  checkout_code:
    docker:
      - image: cimg/base
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  install:
    docker: 
      - image: circleci/golang:1.15
    steps:
      - *restore_repo
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: make install
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - *restore_repo
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: make build-all
      - persist_to_workspace:
          root: bin
          paths:
            - conf-sync-*
  
  test:
    docker:
      - image: circleci/golang:1.15
    steps:
      - *restore_repo
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: make test
  
  lint:
    docker:
      - image: circleci/golang:1.15
    steps:
      - *restore_repo
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
      - run: make lint
  
  release:
    docker:
      - image: circleci/node:14.15
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - *restore_repo
      - attach_workspace:
          at: ~/project/bin/
      - run: make release
  
  sync-readme:
    docker:
      - image: msjpq/sync-dockerhub-readme
    steps:
      - *restore_repo
      - run: python /docker_readme.py --username $DOCKER_REGISTRY_USER --password $DOCKER_REGISTRY_PASSWORD --repo hennersz/conf-sync --readme './README.md'


workflows:
  version: 2

  build-test-release:
    jobs:
      - install
      - lint
      - build: 
          requires: 
            - install
      - test: 
          requires: 
            - install
      - release:
          requires:
            - lint
            - build
            - test
          filters:
            branches:
              only:
                - master
                - beta
                - ci-test
      - sync-readme:
          requires:
            - release